// Code generated by go generate (gen_specs.go). DO NOT EDIT.

package building

import "image"

const (
	Damage_up int = iota
	Critical_chance
	Prayer
	Luck
	Highroll
	Dual_damage_up
	Attack_speed_up
	Striker
	Gambler
	Dual_Prayer
	Dual_damage_way_up
	Critical_damage
	Curse_advantage_ex
	Curse_advantage
	Survivor
	Dual_critical_chance
	Pistol
	Extra_shot
	Dual_curse_advantage
	Change_of_mind
	Homing
	Sync
	Mimic
	Relaxed
	Clumsy
	Scared
	Inaccurate
	Heavy
	Trap
	Lowroll
	Sabotage
	Delicate
	Love
	Procrastination
	Rest
	ItemMax
)

var (
	impls = [ItemMax]*Definition{
		Damage_up: {
			ID:          0,
			Kind:        Common,
			Hand:        SingleHand,
			Name:        "Damage up",
			Description: "+5 flat damage to your %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(0, 0, 128, 128),
		},
		Critical_chance: {
			ID:          1,
			Kind:        Common,
			Hand:        SingleHand,
			Name:        "Critical chance",
			Description: "+5%% critical hit chance (exceeding critical hit chance converts to %% critical damage) to your %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(128, 0, 256, 128),
		},
		Prayer: {
			ID:          2,
			Kind:        Common,
			Hand:        SingleHand,
			Name:        "Prayer",
			Description: "Remove a random curse from your %s and heal for 20%% of your max health.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(256, 0, 384, 128),
		},
		Luck: {
			ID:          3,
			Kind:        Common,
			Hand:        None,
			Name:        "Luck",
			Description: "+2.5% item rarity chance.",
			MaxStacks:   20,
			Rect:        image.Rect(384, 0, 512, 128),
		},
		Highroll: {
			ID:          4,
			Kind:        Common,
			Hand:        None,
			Name:        "Highroll",
			Description: "Re-roll current items present on the floor (does not remove their curses if any).",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(512, 0, 640, 128),
		},
		Dual_damage_up: {
			ID:          5,
			Kind:        Uncommon,
			Hand:        BothHands,
			Name:        "Dual damage up",
			Description: "+2.5 flat damage to %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(640, 0, 768, 128),
		},
		Attack_speed_up: {
			ID:          6,
			Kind:        Uncommon,
			Hand:        BothHands,
			Name:        "Attack speed up",
			Description: "+15%% attack speed to %s.",
			MaxStacks:   6,
			Rect:        image.Rect(768, 0, 896, 128),
		},
		Striker: {
			ID:          7,
			Kind:        Uncommon,
			Hand:        SingleHand,
			Name:        "Striker",
			Description: "Remove all of your attack speed items, gain +5 flat damage to your %s for each removed stack. ",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(0, 128, 128, 256),
		},
		Gambler: {
			ID:          8,
			Kind:        Uncommon,
			Hand:        SingleHand,
			Name:        "Gambler",
			Description: "Remove all of your attack speed items, gain 5%% critical chance to your %s for each removed stack.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(128, 128, 256, 256),
		},
		Dual_Prayer: {
			ID:          9,
			Kind:        Uncommon,
			Hand:        BothHands,
			Name:        "Dual Prayer",
			Description: "Remove a random curse from %s (2 in total) and heal for 20%% of your max health.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(256, 128, 384, 256),
		},
		Dual_damage_way_up: {
			ID:          10,
			Kind:        Rare,
			Hand:        BothHands,
			Name:        "Dual damage way up",
			Description: "+5 flat damage to %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(384, 128, 512, 256),
		},
		Critical_damage: {
			ID:          11,
			Kind:        Rare,
			Hand:        BothHands,
			Name:        "Critical damage",
			Description: "+10%% critical damage to %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(512, 128, 640, 256),
		},
		Curse_advantage_ex: {
			ID:          12,
			Kind:        Rare,
			Hand:        SingleHand,
			Name:        "Curse advantage ex",
			Description: "+5 flat damage to your %s for each active curse in your other hand.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(640, 128, 768, 256),
		},
		Curse_advantage: {
			ID:          13,
			Kind:        Rare,
			Hand:        SingleHand,
			Name:        "Curse advantage",
			Description: "+5 flat damage to your %s for each active curse in this hand.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(768, 128, 896, 256),
		},
		Survivor: {
			ID:          14,
			Kind:        Rare,
			Hand:        SingleHand,
			Name:        "Survivor",
			Description: "+1 flat damage to your %s for each 5 health points missing from 100 (up to +19).",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(0, 256, 128, 384),
		},
		Dual_critical_chance: {
			ID:          15,
			Kind:        Epic,
			Hand:        BothHands,
			Name:        "Dual critical chance",
			Description: "+5%% critical hit chance (exceeding critical hit chance converts to %% critical damage) to %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(128, 256, 256, 384),
		},
		Pistol: {
			ID:          16,
			Kind:        Epic,
			Hand:        SingleHand,
			Name:        "Pistol",
			Description: "Equip a pistol in your %s, shoots a slower piercing projectile dealing damage every tick it is in contact with the target.",
			MaxStacks:   1,
			Rect:        image.Rect(256, 256, 384, 384),
		},
		Extra_shot: {
			ID:          17,
			Kind:        Epic,
			Hand:        SingleHand,
			Name:        "Extra shot",
			Description: "Shoots an additional projectile with your %s",
			MaxStacks:   10,
			Rect:        image.Rect(384, 256, 512, 384),
		},
		Dual_curse_advantage: {
			ID:          18,
			Kind:        Epic,
			Hand:        SingleHand,
			Name:        "Dual curse advantage",
			Description: "+5 flat damage to your %s for each active curse from ALL sources.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(512, 256, 640, 384),
		},
		Change_of_mind: {
			ID:          19,
			Kind:        Epic,
			Hand:        None,
			Name:        "Change of mind",
			Description: "Swap all items (not curses) from both hands.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(640, 256, 768, 384),
		},
		Homing: {
			ID:          20,
			Kind:        Legendary,
			Hand:        SingleHand,
			Name:        "Homing",
			Description: "Projectiles from your %s are homing.",
			MaxStacks:   1,
			Rect:        image.Rect(768, 256, 896, 384),
		},
		Sync: {
			ID:          21,
			Kind:        Legendary,
			Hand:        BothHands,
			Name:        "Sync",
			Description: "Fire %s at the same time.",
			MaxStacks:   1,
			Rect:        image.Rect(0, 384, 128, 512),
		},
		Mimic: {
			ID:          22,
			Kind:        Legendary,
			Hand:        SingleHand,
			Name:        "Mimic",
			Description: "Your %s becomes a perfect clone of your other hand (copies all its items and curses).",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(128, 384, 256, 512),
		},
		Relaxed: {
			ID:          23,
			Kind:        Cursed,
			Hand:        BothHands,
			Name:        "Relaxed",
			Description: "-8%% attack speed to %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(256, 384, 384, 512),
		},
		Clumsy: {
			ID:          24,
			Kind:        Cursed,
			Hand:        SingleHand,
			Name:        "Clumsy",
			Description: "-20%% critical damage to your %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(384, 384, 512, 512),
		},
		Scared: {
			ID:          25,
			Kind:        Cursed,
			Hand:        None,
			Name:        "Scared",
			Description: "-5 maximum health.",
			MaxStacks:   19,
			Rect:        image.Rect(512, 384, 640, 512),
		},
		Inaccurate: {
			ID:          26,
			Kind:        Cursed,
			Hand:        SingleHand,
			Name:        "Inaccurate",
			Description: "Miss 12.5%% more shots with your %s.",
			MaxStacks:   8,
			Rect:        image.Rect(640, 384, 768, 512),
		},
		Heavy: {
			ID:          27,
			Kind:        Cursed,
			Hand:        SingleHand,
			Name:        "Heavy",
			Description: "-12.5%% projectile speed with your %s.",
			MaxStacks:   8,
			Rect:        image.Rect(768, 384, 896, 512),
		},
		Trap: {
			ID:          28,
			Kind:        Cursed,
			Hand:        None,
			Name:        "Trap",
			Description: "Take a hit for 10% of your current health.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(0, 512, 128, 640),
		},
		Lowroll: {
			ID:          29,
			Kind:        Cursed,
			Hand:        None,
			Name:        "Lowroll",
			Description: "Re-roll current items present on the floor (does not remove their curses if any).",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(128, 512, 256, 640),
		},
		Sabotage: {
			ID:          30,
			Kind:        Cursed,
			Hand:        None,
			Name:        "Sabotage",
			Description: "Add 10 extra random curses spread among current items present on the floor.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(256, 512, 384, 640),
		},
		Delicate: {
			ID:          31,
			Kind:        Cursed,
			Hand:        SingleHand,
			Name:        "Delicate",
			Description: "-10 flat damage to your %s.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(384, 512, 512, 640),
		},
		Love: {
			ID:          32,
			Kind:        Cursed,
			Hand:        SingleHand,
			Name:        "Love",
			Description: "When your %s hits the target, the target is pulled closer to you by an additional step.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(512, 512, 640, 640),
		},
		Procrastination: {
			ID:          33,
			Kind:        Cursed,
			Hand:        SingleHand,
			Name:        "Procrastination",
			Description: "The next item you pick for your %s gets an additional random curse.",
			MaxStacks:   1,
			Rect:        image.Rect(640, 512, 768, 640),
		},
		Rest: {
			ID:          34,
			Kind:        Common,
			Hand:        None,
			Name:        "Rest",
			Description: "Recover 1 extra health point after each boss stage.",
			MaxStacks:   InfiniteStacks,
			Rect:        image.Rect(768, 512, 896, 640),
		}}

	commons     = []int{0, 1, 2, 3, 4, 34}
	uncommons   = []int{5, 6, 7, 8, 9}
	rares       = []int{10, 11, 12, 13, 14}
	epics       = []int{15, 16, 17, 18, 19}
	legendaries = []int{20, 21, 22}
	curses      = []int{23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33}
)
